### ISSUE TITLE
Add a nicer icon 

### ISSUE THREAD

**Issue by fredhsu** [aristanetworks/openmgmt#25]
Maybe just use the openconfig icon or something?
https://www.openconfig.net/img/oc-logo-accent.svg

**Comment by ksator** [comment]
I dont know. 
What about adding many icons?  One for each topic we use in this repo? ygot, openconfig, gnmic, ansible, arista, pygnmi, ... and build something with all of them like we did for AVD?

**Comment by sulrich** [comment]
where were we thinking that we needed a nicer icon?  is this from the old jekyll days?

**Comment by fredhsu** [comment]
Yeah I think so

**Comment by sulrich** [comment]
@ksator can we close this, or do you want to sketch something out here  in a draft PR?
