### ISSUE TITLE
simplify the contribution guide described in the README file

### ISSUE THREAD

**Issue by ksator** [aristanetworks/openmgmt#60]

**Comment by sulrich** [comment]
what were you thinking we need to simplify here?

**Comment by ksator** [comment]
Hello 
I added some notes here https://github.com/aristanetworks/openmgmt/pull/73#issuecomment-883610837 about this. 
The idea is to try to simplify it so we get more contributors. 
When I first saw the contribution guide some time ago, I postponed my first contribution ... 
Then the CI, the review process, the maintainers, can fix what need to be fixed.

**Comment by sulrich** [comment]
addressed through #73 - well, the first cut at least.
