### ISSUE TITLE
add topics to the repo

### ISSUE THREAD

**Issue by ksator** [aristanetworks/openmgmt#75]
could you please add some topics to the current list (top right of repo homepage). we dont have permissions :-)  
I suggest you add to the current list these ones: ygot, netconf, restconf, grpcurl, pyang, telemetry, streaming, pygnmi, eos, gnmic, gnoi, go .... The limit is 20.

**Comment by ksator** [comment]
and disable the wiki

**Comment by fredhsu** [comment]
Added topics and removed wiki
