### ISSUE TITLE
doc update

### ISSUE THREAD

**Issue by ksator** [aristanetworks/openmgmt#96]
update the list (some are missing: ygot, ansible ...)
https://github.com/aristanetworks/openmgmt/blob/main/docs/examples/index.md 
https://aristanetworks.github.io/openmgmt/examples/ 

update the README file (moving contributions details in an external contribution guide)

**Comment by sulrich** [comment]
per discussion on 20220121

- move the contributing guidelines from the README and move these into a separate document
- the README should really look like a point of entry that outlines what people can learn from this.
